# Generated by Django 5.0.7 on 2024-07-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
